### ISSUE TITLE
Windows doesn't know how to execute 'fue'

### ISSUE THREAD

**Issue by SYNStack** [dblock/fue#12]
On Windows, `'bundle exec rake'` fails with:

```
2) Fue find default displays version
     Failure/Error: stdout, stderr, status = Open3.capture3(*cmd)

     Errno::ENOEXEC:
       Exec format error - D:/fue/bin/fue
     # ./lib/fue/shell.rb:5:in `system!'
     # ./spec/fue/fue_spec.rb:8:in `block (4 levels) in <top (required)>'
     # ./spec/fue/fue_spec.rb:14:in `block (4 levels) in <top (required)>'
```

**Comment by dblock** [comment]
Closed via https://github.com/dblock/fue/pull/23.
