### ISSUE TITLE
fue exitstatus tests don't work on Windows

### ISSUE THREAD

**Issue by SYNStack** [dblock/fue#13]
Fue::Shell#system! tests fail on Windows because 'echo' prints the entire line. Eg output:
*nix => OK
Windows => OK ; exit 0

```
Failures:

  1) Fue::Shell#system! returns a zero error code
     Failure/Error: expect(Fue::Shell.system!('echo OK ; exit 0')).to eq 'OK'

       expected: "OK"
            got: "OK ; exit 0"

       (compared using ==)
     # ./spec/fue/shell_spec.rb:6:in `block (3 levels) in <top (required)>'

  2) Fue::Shell#system! returns a non zero error code
     Failure/Error:
       expect do
         Fue::Shell.system!('echo OK ; exit 1')
       end.to raise_error RuntimeError, /exit code pid \d* exit 1/

       expected RuntimeError with message matching /exit code pid \d* exit 1/ but nothing was raised
     # ./spec/fue/shell_spec.rb:9:in `block (3 levels) in <top (required)>'
```

**Comment by dblock** [comment]
Closed via https://github.com/dblock/fue/pull/23.
