### ISSUE TITLE
fue_spec fails on Windows when path includes a space

### ISSUE THREAD

**Issue by SYNStack** [dblock/fue#15]
Falsely states that the file doesn't exist, when run from a path with a space. Test passes when run from a path without a space, eg. 'D:\fue"

```
Failures:

  1) Fue find default displays help
     Failure/Error: stdout, stderr, status = Open3.capture3(*cmd)

     Errno::ENOENT:
       No such file or directory - C:/Users/Zack Layton/Documents/Projects/fue/bin/fue
     # ./lib/fue/shell.rb:5:in `system!'
     # ./spec/fue/fue_spec.rb:8:in `block (4 levels) in <top (required)>'
     # ./spec/fue/fue_spec.rb:11:in `block (4 levels) in <top (required)>'

  2) Fue find default displays version
     Failure/Error: stdout, stderr, status = Open3.capture3(*cmd)

     Errno::ENOENT:
       No such file or directory - C:/Users/Zack Layton/Documents/Projects/fue/bin/fue
     # ./lib/fue/shell.rb:5:in `system!'
     # ./spec/fue/fue_spec.rb:8:in `block (4 levels) in <top (required)>'
     # ./spec/fue/fue_spec.rb:14:in `block (4 levels) in <top (required)>'

  3) Fue find help displays help
     Failure/Error: stdout, stderr, status = Open3.capture3(*cmd)

     Errno::ENOENT:
       No such file or directory - C:/Users/Zack Layton/Documents/Projects/fue/bin/fue help
     # ./lib/fue/shell.rb:5:in `system!'
     # ./spec/fue/fue_spec.rb:19:in `block (4 levels) in <top (required)>'
     # ./spec/fue/fue_spec.rb:22:in `block (4 levels) in <top (required)>'

```

**Comment by dblock** [comment]
Needs to just be quoted probably.

**Comment by dblock** [comment]
Closed via https://github.com/dblock/fue/pull/23
